INFERANALYZE= /usr/local/Cellar/infer/0.10.0/lib/infer/infer/bin/InferAnalyze --results-dir '/Users/qitmac000263/Desktop/ios_demo/objective-c/AnimationTest/infer-out' --compilation-database-escaped '/Users/qitmac000263/Desktop/ios_demo/objective-c/AnimationTest/infer-out/clang/cdbe45ce7.json' 

CLUSTERS=cl1 cl2 cl3 cl4 cl5 cl6 cl7 cl8 cl9 cl10 cl11 cl12 cl13 

default: test

all: test

test: $(CLUSTERS)
	@echo

#/Users/qitmac000263/Desktop/ios_demo/objective-c/AnimationTest/infer-out/captured/AppDelegate.m.b1506e5d994c6cea0cd8d84aa5d93bd0
cl1: 
	$(INFERANALYZE) --cluster '/Users/qitmac000263/Desktop/ios_demo/objective-c/AnimationTest/infer-out/multicore/xcl1.cluster'
	@touch $@

#/Users/qitmac000263/Desktop/ios_demo/objective-c/AnimationTest/infer-out/captured/CAPauseTestVC.m.8dd7d5884538f440c3c8448c40d34758
cl2: 
	$(INFERANALYZE) --cluster '/Users/qitmac000263/Desktop/ios_demo/objective-c/AnimationTest/infer-out/multicore/xcl2.cluster'
	@touch $@

#/Users/qitmac000263/Desktop/ios_demo/objective-c/AnimationTest/infer-out/captured/EmitterLayerTestVC.m.7278ac9f85b2934976a6206134b8efb0
cl3: 
	$(INFERANALYZE) --cluster '/Users/qitmac000263/Desktop/ios_demo/objective-c/AnimationTest/infer-out/multicore/xcl3.cluster'
	@touch $@

#/Users/qitmac000263/Desktop/ios_demo/objective-c/AnimationTest/infer-out/captured/main.m.2dce0376678a01403c786603500a3d36
cl4: 
	$(INFERANALYZE) --cluster '/Users/qitmac000263/Desktop/ios_demo/objective-c/AnimationTest/infer-out/multicore/xcl4.cluster'
	@touch $@

#/Users/qitmac000263/Desktop/ios_demo/objective-c/AnimationTest/infer-out/captured/MaskLayerTestVC.m.86f4fd3b6deae9833c8285af7fff30cc
cl5: 
	$(INFERANALYZE) --cluster '/Users/qitmac000263/Desktop/ios_demo/objective-c/AnimationTest/infer-out/multicore/xcl5.cluster'
	@touch $@

#/Users/qitmac000263/Desktop/ios_demo/objective-c/AnimationTest/infer-out/captured/MoveLogoImg.m.0d628c34d9d2b7e36d7016cba4979a38
cl6: 
	$(INFERANALYZE) --cluster '/Users/qitmac000263/Desktop/ios_demo/objective-c/AnimationTest/infer-out/multicore/xcl6.cluster'
	@touch $@

#/Users/qitmac000263/Desktop/ios_demo/objective-c/AnimationTest/infer-out/captured/MyTestLayer.m.3fa6fb6b1016646fbbda9d910886574e
cl7: 
	$(INFERANALYZE) --cluster '/Users/qitmac000263/Desktop/ios_demo/objective-c/AnimationTest/infer-out/multicore/xcl7.cluster'
	@touch $@

#/Users/qitmac000263/Desktop/ios_demo/objective-c/AnimationTest/infer-out/captured/MyTestView.m.f0803bc76707cba7efbc30efd59075df
cl8: 
	$(INFERANALYZE) --cluster '/Users/qitmac000263/Desktop/ios_demo/objective-c/AnimationTest/infer-out/multicore/xcl8.cluster'
	@touch $@

#/Users/qitmac000263/Desktop/ios_demo/objective-c/AnimationTest/infer-out/captured/PMLayerTestVC.m.f70337fe88e9f67f042b7e1762e80fbb
cl9: 
	$(INFERANALYZE) --cluster '/Users/qitmac000263/Desktop/ios_demo/objective-c/AnimationTest/infer-out/multicore/xcl9.cluster'
	@touch $@

#/Users/qitmac000263/Desktop/ios_demo/objective-c/AnimationTest/infer-out/captured/SimpleAnimeVC.m.5b998cdabc9e4cf4f2fe5851039838ae
cl10: 
	$(INFERANALYZE) --cluster '/Users/qitmac000263/Desktop/ios_demo/objective-c/AnimationTest/infer-out/multicore/xcl10.cluster'
	@touch $@

#/Users/qitmac000263/Desktop/ios_demo/objective-c/AnimationTest/infer-out/captured/TimeFuncTestVC.m.6d535f08e79704b1b85e23111dd8bdf1
cl11: 
	$(INFERANALYZE) --cluster '/Users/qitmac000263/Desktop/ios_demo/objective-c/AnimationTest/infer-out/multicore/xcl11.cluster'
	@touch $@

#/Users/qitmac000263/Desktop/ios_demo/objective-c/AnimationTest/infer-out/captured/UIViewAnimationTestVC.m.2eff0db1587bcf5c5793ef5d21304a32
cl12: 
	$(INFERANALYZE) --cluster '/Users/qitmac000263/Desktop/ios_demo/objective-c/AnimationTest/infer-out/multicore/xcl12.cluster'
	@touch $@

#/Users/qitmac000263/Desktop/ios_demo/objective-c/AnimationTest/infer-out/captured/ViewController.m.952b2414f578b0d97ddfc65156b9ac1e
cl13: 
	$(INFERANALYZE) --cluster '/Users/qitmac000263/Desktop/ios_demo/objective-c/AnimationTest/infer-out/multicore/xcl13.cluster'
	@touch $@


clean:
	rm -f $(CLUSTERS)
